ALTER DATABASE paymentdb PRIMARY REGION "us-east1";
ALTER DATABASE paymentdb ADD REGION "us-east2";
ALTER DATABASE paymentdb ADD REGION "us-west2";

ALTER TABLE Embossing SET LOCALITY REGIONAL BY ROW AS CCREGION;

ALTER TABLE EMBOSSING ADD COLUMN CCREGION crdb_internal_region AS (
 CASE
 WHEN BINNUM IN (443112) THEN 'us-east1'
 WHEN BINNUM IN (467584) THEN 'us-east2'
 WHEN BINNUM IN (525363) THEN 'us-west2' 
 END
) STORED;
ALTER TABLE Embossing ALTER COLUMN REGION SET NOT NULL;

ALTER TABLE account SET LOCALITY REGIONAL BY ROW AS CCREGION
ALTER TABLE address SET LOCALITY REGIONAL BY ROW AS CCREGION
ALTER TABLE apilog SET LOCALITY REGIONAL BY ROW AS CCREGION
ALTER TABLE cblog SET LOCALITY REGIONAL BY ROW AS CCREGION
ALTER TABLE customer SET LOCALITY REGIONAL BY ROW AS CCREGION

ALTER TABLE logartxn SET LOCALITY REGIONAL BY ROW AS CCREGION
ALTER TABLE loyaltyplan SET LOCALITY REGIONAL BY ROW AS CCREGION
ALTER TABLE plansegment SET LOCALITY REGIONAL BY ROW AS CCREGION
ALTER TABLE testtable SET LOCALITY REGIONAL BY ROW AS CCREGION
ALTER TABLE trans_in_acct SET LOCALITY REGIONAL BY ROW AS CCREGION



